export const GET_MOVIE_LIST = 'GET_MOVIE_LIST';

export const GET_MOVIE_TRAILER = 'GET_MOVIE_TRAILER';

export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';

export const SHOW_LOGINSIGNUP_COMPONENT = 'SHOW_LOGINSIGNUP_COMPONENT';

export const GET_CHAIR_LIST = 'GET_CHAIR_LIST';

export const CHOICE_CHAIR = 'CHOICE_CHAIR';

export const GET_USER_INFO = 'GET_USER_INFO';

export const GET_USER_LIST = 'GET_USER_LIST';
